Repository kahluaband/Homepage_BE_20th, pull requests merged in 2023-08, with the labels that each got.

#8 #1 Feat: add freshman_ticket create
  application/views.py
  tickets/serializers.py
  tickets/urls.py
  tickets/views.py
Labels: task

#10 #1 Fix : remove ordercompleteserializer in ticket.views
  application/views.py
  tickets/serializers.py
  tickets/urls.py
  tickets/views.py
Labels: bug

#16 Logout
  .gitignore
  users/urls.py
  users/views/base_views.py
Labels: task

#14 #1 Feat: calculate price in general ticket
  tickets/migrations/0003_generalticket_reservation_id.py
  tickets/models.py
  tickets/serializers.py
  tickets/urls.py
  tickets/views/views.py
Labels: task

#20 #19 Feat: add env file and settings about env
  kahluaproject/settings.py
Labels: enhancement

#24 #19 Feat: add NCP secret key in settings.py
  kahluaproject/settings.py
  users/views/base_views.py
Labels: enhancement

#26 #25 feat: cancel freshman, general tickets
  tickets/urls.py
  tickets/views/views.py
Labels: task

#27 #25 Feat: change the way to get id to reservation number
  tickets/urls.py
  tickets/views/views.py
Labels: task

#22 #21 Feat: add send_message function in tickets
  kahluaproject/settings.py
  tickets/views/send_msg.py
  tickets/views/views.py
Labels: task
